"""Kill switches at drawdown, instrument, strategy and system level (PRD s.9, R6).

A trip at any level is *enforced by the risk gateway* (it consults ``entry_block_reasons`` on
every intent), not by the component that failed. Flatten / reduce actions are queued in
``actions_due`` and executed by the engine as risk-reducing orders through the gateway.

Reset rules (PRD s.9):
* Worsening is automatic; recovery is never automatic for drawdown, strategy hard-stop or
  system trips. A manual reset needs a written reason, a cooling-off delay and a confirmation.
* Red and Black drawdown resets require an external one-time code (stored only as SHA-256
  hashes in configuration, generated by a second person or device).
* Only data-health instrument trips may auto-reset, after a period of clean data.
"""

from __future__ import annotations

import enum
import hashlib
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Callable

from ..core.audit import AuditLog
from ..core.config import KillSwitchConfig, LadderStep, PortfolioConfig


class KSLevel(str, enum.Enum):
    SYSTEM = "system"
    DRAWDOWN = "drawdown"
    STRATEGY = "strategy"
    INSTRUMENT = "instrument"


class KSAction(enum.IntEnum):
    """Actions from mildest to strongest."""

    NONE = 0
    WARN = 1           # alert only
    BLOCK_ENTRIES = 2  # no new risk; exits and hedges allowed
    REDUCE = 3         # cut affected positions by a fraction
    FLATTEN = 4        # cancel open orders and close affected positions
    HALT = 5           # flatten, then lock the scope until a manual reset


_ACTION_NAMES = {"warn": KSAction.WARN, "block": KSAction.BLOCK_ENTRIES, "reduce": KSAction.WARN,
                 "flatten": KSAction.FLATTEN, "halt": KSAction.HALT}


@dataclass
class Trip:
    level: KSLevel
    scope: str                       # "system" | "account" | strategy id | instrument key
    action: KSAction
    reason: str
    ts: datetime
    values: dict[str, Any] = field(default_factory=dict)
    manual_reset: bool = True
    external_key: bool = False
    data_health: bool = False
    executed: bool = False           # flatten / reduce carried out
    risk_multiplier: float = 1.0     # e.g. soft stop halves the strategy budget
    until: datetime | None = None    # suspension / halt period end
    reset_requested_at: datetime | None = None
    reset_reason: str = ""
    reset_actor: str = ""
    clean_since: datetime | None = None

    @property
    def key(self) -> tuple[KSLevel, str]:
        return self.level, self.scope


class KillSwitchManager:
    def __init__(self, cfg: KillSwitchConfig, portfolio: PortfolioConfig, audit: AuditLog,
                 clock: Callable[[], datetime], persist: Callable[[list[dict]], None] | None = None):
        self.cfg = cfg
        self.portfolio = portfolio
        self.audit = audit
        self.clock = clock
        self._persist = persist
        self.trips: dict[tuple[KSLevel, str], Trip] = {}
        self.ladder_state = "GREEN"
        self.ladder_peak: float | None = None     # high-water mark used by the ladder
        self.used_codes: set[str] = set()
        self._instrument_trips: dict[str, list[datetime]] = {}
        self._strategy_trips: list[datetime] = []
        self.drill_mode = False

    # -- tripping --------------------------------------------------------------------------
    def trip(self, level: KSLevel, scope: str, action: KSAction, reason: str,
             values: dict[str, Any] | None = None, *, data_health: bool = False,
             external_key: bool = False, risk_multiplier: float = 1.0,
             until: datetime | None = None, strategy_id: str | None = None,
             actor: str = "auto") -> Trip:
        """Trip (or escalate) a kill switch. A trip never weakens an existing one."""
        now = self.clock()
        existing = self.trips.get((level, scope))
        if existing and existing.action >= action and existing.risk_multiplier <= risk_multiplier:
            return existing
        trip = Trip(level=level, scope=scope, action=max(action, existing.action if existing else action),
                    reason=reason, ts=now, values=values or {},
                    manual_reset=not data_health, external_key=external_key or bool(
                        existing and existing.external_key),
                    data_health=data_health and not (existing and not existing.data_health),
                    risk_multiplier=min(risk_multiplier, existing.risk_multiplier if existing else 1.0),
                    until=until)
        self.trips[trip.key] = trip
        self.audit.record("killswitch_trip", actor, {
            "level": level.value, "scope": scope, "action": trip.action.name, "reason": reason,
            "values": values or {}, "drill": self.drill_mode}, ts=now)
        if trip.action >= KSAction.BLOCK_ENTRIES:
            self._escalate(level, scope, strategy_id, now)
        self._save()
        return trip

    def _escalate(self, level: KSLevel, scope: str, strategy_id: str | None, now: datetime) -> None:
        """Repeated instrument trips -> strategy trip; repeated strategy trips -> drawdown level.

        Only blocking trips count, inside a rolling window of ``escalate_window_days``.
        """
        horizon = now - timedelta(days=self.cfg.escalate_window_days)
        if level is KSLevel.INSTRUMENT and strategy_id:
            hist = [t for t in self._instrument_trips.get(strategy_id, []) if t >= horizon] + [now]
            self._instrument_trips[strategy_id] = hist
            if len(hist) >= self.cfg.escalate_instrument_trips:
                self._instrument_trips[strategy_id] = []
                self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                          f"escalation: {len(hist)} instrument trips")
        elif level is KSLevel.STRATEGY:
            self._strategy_trips = [t for t in self._strategy_trips if t >= horizon] + [now]
            if len(self._strategy_trips) >= self.cfg.escalate_strategy_trips:
                self._strategy_trips = []
                self.trip(KSLevel.DRAWDOWN, "account", KSAction.BLOCK_ENTRIES,
                          "escalation: repeated strategy trips")

    def manual_kill(self, actor: str = "operator", flatten: bool = False) -> Trip:
        """The operator's big red button (FR-9.4). Works without market data."""
        return self.trip(KSLevel.SYSTEM, "system", KSAction.FLATTEN if flatten else KSAction.BLOCK_ENTRIES,
                         "manual system kill", actor=actor)

    # -- queries used by the gateway and strategies ----------------------------------------
    def active(self, level: KSLevel | None = None) -> list[Trip]:
        return [t for t in self.trips.values() if level is None or t.level is level]

    def entry_block_reasons(self, strategy_id: str, instrument: str | None = None) -> list[str]:
        """Every reason new risk is blocked for this strategy / instrument right now."""
        now = self.clock()
        reasons = []
        for t in self.trips.values():
            if t.action < KSAction.BLOCK_ENTRIES and not (t.until and now < t.until):
                continue
            if (t.level is KSLevel.SYSTEM
                    or (t.level is KSLevel.DRAWDOWN and t.scope == "account")
                    or (t.level is KSLevel.STRATEGY and t.scope == strategy_id)
                    or (t.level is KSLevel.INSTRUMENT and t.scope == instrument)):
                reasons.append(f"{t.level.value}:{t.scope} {t.action.name} ({t.reason})")
        # Orange and worse: designated high-tail-risk strategies are stopped.
        step = self._ladder_step(self.ladder_state)
        alloc = self.portfolio.strategies.get(strategy_id)
        if step and step.stop_high_tail and alloc and alloc.high_tail_risk:
            reasons.append(f"drawdown {self.ladder_state}: high-tail-risk strategies stopped")
        return reasons

    def risk_multiplier(self, strategy_id: str | None = None) -> float:
        """Combined budget multiplier from the drawdown ladder and strategy soft stops."""
        m = 1.0
        step = self._ladder_step(self.ladder_state)
        if step:
            m *= step.risk_multiplier
        for t in self.trips.values():
            if t.level is KSLevel.DRAWDOWN or (t.level is KSLevel.STRATEGY and t.scope == strategy_id):
                m *= t.risk_multiplier
        return m

    def actions_due(self) -> list[Trip]:
        """Trips whose reduce / flatten / halt action has not been executed yet."""
        return [t for t in self.trips.values() if t.action >= KSAction.FLATTEN and not t.executed]

    def mark_executed(self, trip: Trip) -> None:
        trip.executed = True
        self.audit.record("killswitch_executed", "engine",
                          {"level": trip.level.value, "scope": trip.scope}, ts=self.clock())
        self._save()

    # -- automatic evaluation --------------------------------------------------------------
    def _ladder_step(self, state: str) -> LadderStep | None:
        return next((s for s in self.cfg.ladder if s.state == state), None)

    def evaluate_account(self, equity: float, day_start_equity: float, week_start_equity: float) -> str:
        """Drawdown ladder plus daily / weekly loss limits. Returns the ladder state."""
        if self.ladder_peak is None or equity > self.ladder_peak:
            self.ladder_peak = equity
        dd_pct = (equity / self.ladder_peak - 1.0) * 100.0
        # Worst step whose threshold is breached.
        breached = [s for s in self.cfg.ladder if dd_pct <= s.drawdown_pct]
        target = min(breached, key=lambda s: s.drawdown_pct) if breached else None
        current = self._ladder_step(self.ladder_state)
        if target and (current is None or target.drawdown_pct < current.drawdown_pct):
            # Worsening is automatic.
            self.ladder_state = target.state
            action = _ACTION_NAMES.get(target.action, KSAction.WARN)
            until = self.clock() + timedelta(days=target.halt_days) if target.halt_days else None
            self.trip(KSLevel.DRAWDOWN, "account", action,
                      f"drawdown {dd_pct:.2f}% -> {target.state}",
                      {"equity": equity, "peak": self.ladder_peak, "dd_pct": dd_pct},
                      external_key=target.require_external_key, until=until)
        day_loss = (equity / day_start_equity - 1.0) * 100.0 if day_start_equity else 0.0
        if day_loss <= -self.cfg.daily_loss_pct:
            self.trip(KSLevel.DRAWDOWN, "account", KSAction.BLOCK_ENTRIES,
                      f"daily loss {day_loss:.2f}% beyond {self.cfg.daily_loss_pct}%",
                      {"equity": equity, "day_start": day_start_equity})
        week_loss = (equity / week_start_equity - 1.0) * 100.0 if week_start_equity else 0.0
        if week_loss <= -self.cfg.weekly_loss_pct:
            self.trip(KSLevel.DRAWDOWN, "account", KSAction.BLOCK_ENTRIES,
                      f"weekly loss {week_loss:.2f}% beyond {self.cfg.weekly_loss_pct}%",
                      {"equity": equity, "week_start": week_start_equity})
        return self.ladder_state

    def evaluate_strategy(self, strategy_id: str, pnl: float, peak_pnl: float, nav: float,
                          stats: Any) -> None:
        """Strategy-level triggers (strategy doc s.4 defaults, PRD s.9)."""
        alloc = self.portfolio.strategies.get(strategy_id)
        if alloc is None or nav <= 0:
            return
        kcfg = self.cfg.strategies.get(strategy_id)
        dd_pct = (peak_pnl - pnl) / nav * 100.0
        soft = alloc.soft_stop_pct if alloc.soft_stop_pct is not None else 0.6 * alloc.hard_stop_pct
        if dd_pct >= alloc.hard_stop_pct:
            self.trip(KSLevel.STRATEGY, strategy_id, KSAction.FLATTEN,
                      f"hard stop: strategy drawdown {dd_pct:.2f}% of NAV >= {alloc.hard_stop_pct}%",
                      {"pnl": pnl, "peak": peak_pnl})
        elif dd_pct >= soft:
            self.trip(KSLevel.STRATEGY, strategy_id, KSAction.WARN,
                      f"soft stop: strategy drawdown {dd_pct:.2f}% of NAV >= {soft:.2f}%",
                      {"pnl": pnl, "peak": peak_pnl}, risk_multiplier=0.5)
        if kcfg is None or stats is None:
            return
        if stats.loss_streak > kcfg.max_loss_streak:
            self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                      f"loss streak {stats.loss_streak} > {kcfg.max_loss_streak}")
        if stats.n_trades >= kcfg.min_trades_for_drift:
            if stats.slippage_ratio is not None and stats.slippage_ratio > kcfg.max_slippage_ratio:
                self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                          f"slippage {stats.slippage_ratio:.2f}x assumption")
            if kcfg.hit_rate_band and not (kcfg.hit_rate_band[0] <= stats.hit_rate <= kcfg.hit_rate_band[1]):
                self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                          f"hit rate {stats.hit_rate:.2f} outside backtest band {kcfg.hit_rate_band}")
            if (kcfg.avg_loss_to_win_max and stats.avg_win_recent > 0
                    and stats.avg_loss_recent > kcfg.avg_loss_to_win_max * stats.avg_win_recent):
                self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                          "average loss over last 20 trades above "
                          f"{kcfg.avg_loss_to_win_max}x average win")
        if stats.open_trades >= 2 and stats.red_share > kcfg.max_red_share:
            self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                      f"{stats.red_share:.0%} of open trades off-thesis")
        if stats.rejections > kcfg.max_rejections:
            self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                      f"{stats.rejections} order rejections")
        if kcfg.full_loss_suspend_days and stats.last_full_loss is not None:
            until = stats.last_full_loss + timedelta(days=kcfg.full_loss_suspend_days)
            if self.clock() < until and (KSLevel.STRATEGY, strategy_id) not in self.trips:
                self.trip(KSLevel.STRATEGY, strategy_id, KSAction.BLOCK_ENTRIES,
                          f"full-loss structure: suspended for review until {until:%Y-%m-%d}",
                          until=until)

    def instrument_data_fault(self, instrument: str, reason: str, strategy_id: str | None = None) -> None:
        """Stale or failed-cross-check data: block entries; eligible for auto-reset."""
        self.trip(KSLevel.INSTRUMENT, instrument, KSAction.BLOCK_ENTRIES, reason,
                  data_health=True, strategy_id=strategy_id)

    def instrument_data_clean(self, instrument: str) -> None:
        """Called when data for the instrument is healthy again; may auto-reset (PRD s.9)."""
        t = self.trips.get((KSLevel.INSTRUMENT, instrument))
        if not t or not t.data_health or not self.cfg.data_auto_reset_enabled:
            return
        now = self.clock()
        t.clean_since = t.clean_since or now
        if now - t.clean_since >= timedelta(minutes=self.cfg.data_auto_reset_minutes):
            del self.trips[t.key]
            self.audit.record("killswitch_reset", "auto",
                              {"level": t.level.value, "scope": t.scope, "reason": "data clean"}, ts=now)
            self._save()

    # -- manual reset workflow -------------------------------------------------------------
    def request_reset(self, level: KSLevel, scope: str, reason: str, actor: str) -> str:
        t = self.trips.get((level, scope))
        if t is None:
            return "no such trip"
        if not reason.strip():
            return "a written reason is required"
        t.reset_requested_at = self.clock()
        t.reset_reason, t.reset_actor = reason, actor
        self.audit.record("killswitch_reset_requested", actor,
                          {"level": level.value, "scope": scope, "reason": reason}, ts=t.reset_requested_at)
        self._save()
        return f"cooling-off {self.cfg.reset_cooloff_minutes} min started"

    def confirm_reset(self, level: KSLevel, scope: str, actor: str, external_code: str | None = None,
                      equity: float | None = None) -> tuple[bool, str]:
        t = self.trips.get((level, scope))
        if t is None:
            return False, "no such trip"
        now = self.clock()
        if t.reset_requested_at is None:
            return False, "request_reset first (reason required)"
        if now - t.reset_requested_at < timedelta(minutes=self.cfg.reset_cooloff_minutes):
            return False, "cooling-off period has not elapsed"
        if t.until and now < t.until:
            return False, f"halt period runs until {t.until:%Y-%m-%d}"
        if t.external_key:
            if not external_code:
                return False, "external reset key required"
            digest = hashlib.sha256(external_code.encode()).hexdigest()
            if digest not in self.cfg.external_reset_code_hashes or digest in self.used_codes:
                return False, "invalid or already-used external code"
            self.used_codes.add(digest)
        del self.trips[t.key]
        if level is KSLevel.DRAWDOWN:
            # Re-base the ladder so the same drawdown does not immediately re-trip.
            self.ladder_state = "GREEN"
            if equity is not None:
                self.ladder_peak = equity
        self.audit.record("killswitch_reset", actor, {"level": level.value, "scope": scope,
                                                      "reason": t.reset_reason}, ts=now)
        self._save()
        return True, "reset"

    def simulate_operator_resets(self, equity: float) -> list[Trip]:
        """BACKTEST ONLY: reset manual trips older than ``backtest_auto_reset_days``.

        Logged as ``simulated_reset`` so research output never hides that a reset happened.
        """
        days = self.cfg.backtest_auto_reset_days
        if days is None:
            return []
        now = self.clock()
        done = []
        for t in list(self.trips.values()):
            if t.data_health or (t.until and now < t.until):
                continue
            if t.level is KSLevel.DRAWDOWN and self.ladder_state == "BLACK" and not self.cfg.backtest_reset_black:
                continue
            if now - t.ts < timedelta(days=days):
                continue
            del self.trips[t.key]
            if t.level is KSLevel.DRAWDOWN:
                self.ladder_state, self.ladder_peak = "GREEN", equity
            self.audit.record("simulated_reset", "backtest", {"level": t.level.value, "scope": t.scope,
                              "reason": t.reason}, ts=now)
            done.append(t)
        return done

    # -- persistence -----------------------------------------------------------------------
    def to_dicts(self) -> list[dict[str, Any]]:
        out = []
        for t in self.trips.values():
            d = dict(t.__dict__)
            d["level"], d["action"] = t.level.value, int(t.action)
            out.append(d)
        return out

    def load(self, rows: list[dict[str, Any]], ladder_state: str = "GREEN",
             ladder_peak: float | None = None) -> None:
        self.trips.clear()
        for d in rows:
            d = dict(d)
            d["level"], d["action"] = KSLevel(d["level"]), KSAction(d["action"])
            for k in ("ts", "until", "reset_requested_at", "clean_since"):
                if isinstance(d.get(k), str):
                    d[k] = datetime.fromisoformat(d[k])
            t = Trip(**d)
            self.trips[t.key] = t
        self.ladder_state, self.ladder_peak = ladder_state, ladder_peak

    def _save(self) -> None:
        if self._persist:
            self._persist(self.to_dicts())
